# Generated by Django 4.0.4 on 2022-06-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_formcontacto_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='mesage',
            new_name='message',
        ),
    ]
