# Generated by Django 4.0.4 on 2022-06-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_mesage_contacto_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='message',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
